package Chapter3;

import java.util.Scanner;

/**
 * Program to display if user guesses the random number generated by the program correctly
 *
 * @author Vinayak Gopakumar
 */
public class C3_14 {

    /**
     * Main Method
     *
     * @param args arguments from command line prompt
     */
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);

        //Number generator
        int x = (int) (Math.random() * 2);
        System.out.print("Enter 1 for heads or 0 for tails");
        int y = input.nextInt();

        if (x == y) {
            System.out.print("Correct");
        } else {
            System.out.print("Incorrect");

        }

    }
}
